double fmod(double x, double y);
double fabs(double x);
double floor(double x);
double atan2(double y, double x);
double tan(double x);
double sqrt(double x);
double sin(double x);
double log(double x);
double exp(double x);
double cos(double x);
double ceil(double x);
double atan(double x);
double asin(double x);
double acos(double x);
double pow(double x, double y);
double fmax(double x, double y);
double fmin(double x, double y);